### ISSUE TITLE
Щ

### ISSUE THREAD

**Issue by Vasai1985** [fartem/adaptive-recycler-view#7]
**Describe the bug**

**To Reproduce**
1. Go to '...';
2. Click on '....';
3. Scroll down to '....';
4. See error.

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
-  Device: [e.g. Xiaomi Mi A1]
-  OS: [e.g. Android 8.1]
-  Version [e.g. 2.9.9.3]

**Additional context**

**Comment by fartem** [comment]
Can you describe your bug?

**Comment by fartem** [comment]
No response.
